## Submenu, which is specific to this module onky
scripts:
  label: Scripts
  route: reset_scripts_path
  access_level: 1
targets:
  label: Targets
  route: reset_targets_path
  access_level: 1
target_groups:
  label: Target Groups
  route: target_groups_path
  access_level: 1
notifications:
  label: Notifications
  route: notify_groups_path
  access_level: 1
servers:
  label: Servers
  route: servers_path
  access_level: 1
target_types:
  label: Target Types
  route: target_types_path
  access_level: 1
script_categories:
  label: Script Categories
  route: script_categories_path
  access_level: 1
users:
  label: Users
  route: users_path
  access_level: 0
