insert into psd_notify_group(notify_group_id,name,create_sysdate,update_sysdate)
select notify_group_id,name,create_sysdate,update_sysdate from tmp_psd_notify_group
;
insert into psd_notify_group_email(notify_group_email_id,notify_group_id,severity,email_address,create_sysdate,update_sysdate)
select notify_group_email_id,notify_group_id,severity,email_address,create_sysdate,update_sysdate from tmp_psd_notify_group_email
;
insert into psd_query_column(query_column_id,script_id,column_position,column_name_str,create_sysdate,update_sysdate)
select query_column_id,script_id,column_position,column_name_str,create_sysdate,update_sysdate from tmp_psd_query_column
;
insert into psd_script(script_id,name,description,schedule_min,schedule_hour,schedule_day,schedule_month,schedule_week,query_type,query_text,fixed_severity,severity_column_position,value_med_severity,value_high_severity,expression_text,message_format,message_subject,message_header,message_text_str,message_footer,status_code,create_sysdate,update_sysdate,timeout_sec)
select script_id,name,description,schedule_min,schedule_hour,schedule_day,schedule_month,schedule_week,query_type,query_text,fixed_severity,severity_column_position,value_med_severity,value_high_severity,expression_text,message_format,message_subject,message_header,message_text_str,message_footer,status_code,create_sysdate,update_sysdate,timeout_sec from tmp_psd_script
;
insert into psd_script_category(script_category_id,name,create_sysdate,update_sysdate)
select script_category_id,name,create_sysdate,update_sysdate from tmp_psd_script_category
;
insert into psd_script_category_assign(script_category_assign_id,script_category_id,script_id,create_sysdate,update_sysdate)
select script_category_assign_id,script_category_id,script_id,create_sysdate,update_sysdate from tmp_psd_script_category_assign
;
insert into psd_script_group(script_group_id,script_id,target_group_id,create_sysdate,update_sysdate)
select script_group_id,script_id,target_group_id,create_sysdate,update_sysdate from tmp_psd_script_group
;
insert into psd_script_log(script_log_id,script_id,start_date,finish_date,status_number,error_status_code,trigger_status_code,create_sysdate,update_sysdate)
select script_log_id,script_id,start_date,finish_date,status_number,error_status_code,trigger_status_code,create_sysdate,update_sysdate from tmp_psd_script_log
;
insert into psd_script_notification(script_notification_id,notify_group_id,script_id,create_sysdate,update_sysdate)
select script_notification_id,notify_group_id,script_id,create_sysdate,update_sysdate from tmp_psd_script_notification
;
insert into psd_script_person_notification(script_person_notification_id,script_id,email_address,create_sysdate,update_sysdate)
select script_person_notification_id,script_id,email_address,create_sysdate,update_sysdate from tmp_psd_script_person_notification
;
insert into psd_script_target(script_target_id,script_id,target_id,create_sysdate,update_sysdate)
select script_target_id,script_id,target_id,create_sysdate,update_sysdate from tmp_psd_script_target
;
insert into psd_script_target_col_log(script_target_col_log_id,script_target_row_log_id,column_number,column_value,create_sysdate,update_sysdate)
select script_target_col_log_id,script_target_row_log_id,column_number,column_value,create_sysdate,update_sysdate from tmp_psd_script_target_col_log
;
insert into psd_script_target_log(script_target_log_id,script_log_id,target_id,start_date,finish_date,status_number,error_message,severity,create_sysdate,update_sysdate)
select script_target_log_id,script_log_id,target_id,start_date,finish_date,status_number,error_message,severity,create_sysdate,update_sysdate from tmp_psd_script_target_log
;
insert into psd_script_target_row_log(script_target_row_log_id,script_target_log_id,row_number,expression_result,expression_error_message,severity,create_sysdate,update_sysdate)
select script_target_row_log_id,script_target_log_id,row_number,expression_result,expression_error_message,severity,create_sysdate,update_sysdate from tmp_psd_script_target_row_log
;
insert into psd_server(server_id,name,status_code,create_sysdate,update_sysdate,location,heartbeat_sysdate)
select server_id,name,status_code,create_sysdate,update_sysdate,location,heartbeat_sysdate from tmp_psd_server
;
insert into psd_target(target_id,target_type_id,name,hostname,port_number,database_name,monitor_username,monitor_password,status_code,inactive_until,create_sysdate,update_sysdate,server_id)
select target_id,target_type_id,name,hostname,port_number,database_name,monitor_username,monitor_password,status_code,inactive_until,create_sysdate,update_sysdate,server_id from tmp_psd_target
;
insert into psd_target_group(target_group_id,name,create_sysdate,update_sysdate)
select target_group_id,name,create_sysdate,update_sysdate from tmp_psd_target_group
;
insert into psd_target_group_assignment(target_group_assignment_id,target_group_id,target_id,create_sysdate,update_sysdate,status_code,inactive_until)
select target_group_assignment_id,target_group_id,target_id,create_sysdate,update_sysdate,status_code,inactive_until from tmp_psd_target_group_assignment
;
insert into psd_target_hostname(target_hostname_id,target_id,hostname,create_sysdate,update_sysdate)
select target_hostname_id,target_id,hostname,create_sysdate,update_sysdate from tmp_psd_target_hostname
;
